language: go
sudo: required
go:
  - 1.11.1
  - tip
env:
  global:
    - GO_FOR_RELEASE=1.11.1
    - IMAGE_NAME=tsuru/planb
  matrix:
    - GOARCH=amd64
addons:
  apt:
    packages:
      - rpm
install:
  - true
script:
  - go test -short -race ./...
  - CGO_ENABLED=0 go build
after_success:
  - curl https://raw.githubusercontent.com/tsuru/push-to-docker/master/push.sh | bash
  - test -n "$TRAVIS_TAG" && curl -sL https://raw.githubusercontent.com/tsuru/push-to-packagecloud/master/push.sh | PACKAGE_NAME=planb bash
services:
  - redis-server
  - docker
matrix:
  allow_failures:
    - go: tip
notifications:
  slack:
    secure: kCYIZs8J3NhrIlwR5fT9704UUeERAsNroU5FAlAi+Nk/GYWcRnxxt2Wc6AUkFCR+3Mei8c0fEZy8hejmn+UDgxCY0nln0l/g4Lmv47NsULsp9y1YQdxD1GGRLrSUPvYRBtEpog3K7+X/amb3pjzOjqrOY3n5vWGT9yagyLk95Fc=
